
platform :ios, '9.0' #手机的系统
use_frameworks!

target 'QHAwemeDemo' do
  #私有组件

#pod 'NicooEnptyView'
pod 'NicooNetwork' # 网络请求组件

 # 第三方组件
pod 'IQKeyboardManagerSwift', '~> 6.4.2'
pod 'MJRefresh', '~> 3.1.14.1'
pod 'MBProgressHUD','~> 1.1.0'
pod 'SnapKit'
pod 'KeychainSwift'
pod 'DouYPlayer'
pod 'DouYinScan'
pod 'GPUImage'

#pod 'Firebase/Core'

end

